const translations = {
    "en": {
        "home": "Home",
        "spanish": "Español",
        "heroTitle": "Get the Fair Compensation You Deserve",
        "noRecovery": "No Recovery, No Fee",
        "heroSubtitle": "We Fight for You and Your Rights as a Policyholder",
        "heroDescription": "Florida-based public adjusters dedicated to helping property owners maximize their insurance claims.",
        "freeInspection": "Free Inspection",
        "servicesTitle": "Services Listing",
        "floodDamage": "Flood Damage",
        "floodDescription": "We handle flood damage claims to help you recover quickly and efficiently.",
        "fireDamage": "Fire Damage",
        "fireDescription": "Our experts assist with fire damage claims to restore your property.",
        "moldRemediation": "Mold Remediation",
        "moldDescription": "We specialize in mold damage claims to ensure a safe environment.",
        "hurricaneDamage": "Hurricane Damage",
        "hurricaneDescription": "We help you recover from hurricane damage with expert claim handling.",
        "waterDamage": "Water Damage",
        "waterDescription": "Our team handles water damage claims to restore your property.",
        "vandalismClaims": "Vandalism Claims",
        "vandalismDescription": "We assist with vandalism claims to help you recover from property damage.",
        "exploreMoreServices": "More Information",
        "aboutTitle": "#1 Trusted Partner for Insurance Claims",
        "aboutDescription": "Dynamic Claims Advisors Inc. is dedicated to providing expert advice and personalized support in navigating insurance claims. We help individuals and businesses achieve fair outcomes efficiently.",
        "aboutList1": "Expert Guidance for All Claim Types",
        "aboutList2": "Transparent and Professional Service",
        "aboutList3": "Committed to Client Success",
        "aboutButton": "Learn More About Us",
        "contactTitle": "Contact Us",
        "contactDescription": "We are here to help. Get in touch with us for inquiries, support, or any other assistance you may need.",
        "contactFormDescription": "Request your Free Inspection",
        "contactFormName": "Your Name",
        "contactFormEmail": "Your Email",
        "contactFormSubject": "Subject",
        "contactFormPhone": "Phone Number",
        "contactFormMessage": "Message",
        "contactFormNamePlaceholder": "Your Name",
        "contactFormEmailPlaceholder": "Your Email",
        "contactFormPhonePlaceholder": "Phone",
        "contactFormMessagePlaceholder": "Leave a message here",
        "contactFormButton": "Send Message",
        "ctaTitle": "Connect With Our Expert Team",
        "ctaDescription": "We are here to assist you. Contact us to learn more about our services or to schedule a consultation.",
        "ctaCallButton": "Make A Call",
        "ctaAppointmentButton": "Book Appointment",
        "easyClaimTitle": "Making Claims Has Never Been Easier",
        "easyClaimDescription": "Our streamlined process is designed so you don’t have to worry about the details. From start to finish, we guide you every step of the way.",
        "easyClaimList1": "Free Evaluation: Begin with a free inspection and consultation.",
        "easyClaimList2": "Documentation :We handle all the required paperwork for you.",
        "easyClaimList3": "Negotiation: We work directly with your insurance company to maximize your claim.",
        "easyClaimList4": "Fast Resolution: Receive your compensation quickly and hassle-free.",
        "easyClaimButton": "Get Started Now",
        "testimonialTitle": "What Our Clients Say",
        "testimonial1": "\"After our house was damaged by a hurricane, this team guided us every step of the way. Their professionalism and care made a stressful process so much easier. Highly recommend!\"",
        "testimonial2": "\"Thanks to their expertise, we received the full compensation for the water damage in our basement. The team is efficient, friendly, and truly knows what they’re doing.\"",
        "testimonial3": "\"I never thought filing an insurance claim could be this smooth. Their attention to detail and constant communication gave me peace of mind after the fire damage to my property.\"",
        "footerGetInTouch": "Get In Touch",
        "footerQuickLinks": "Quick Links",
        "footerAboutUs": "About Us",
        "footerContactUs": "Contact Us",
        "footerOurServices": "Our Services",
        "footerPrivacyPolicy": "Privacy Policy",
        "footerTermsConditions": "Terms & Conditions",
        "footerNewsletter": "Newsletter",
        "footerNewsletterDescription": "Stay updated with our latest news and offers.",
        "footerNewsletterPlaceholder": "Your email",
        "footerNewsletterButton": "Sign Up",
        "servicesPageTitle": "Our Services",
        "floodLongDescription": "Flood damage can be devastating, but our team is here to help you recover quickly and efficiently. We handle all aspects of flood damage claims, from initial assessment to final settlement. Our experts work tirelessly to ensure you receive the compensation you deserve.",
        "fireLongDescription": "Fire damage can leave your property in ruins, but our team is here to guide you through the recovery process. We assist with fire damage claims, helping you restore your property and get back on your feet. Our goal is to make the process as smooth and stress-free as possible.",
        "moldLongDescription": "Mold can pose serious health risks and damage your property. Our team specializes in mold damage claims, ensuring a safe and healthy environment for you and your family. We handle all the necessary steps to resolve mold issues efficiently.",
        "hurricaneLongDescription": "Hurricanes can cause extensive damage to your property. Our team is experienced in handling hurricane damage claims, helping you recover and rebuild. We work directly with your insurance company to maximize your claim and ensure a fast resolution.",
        "waterLongDescription": "Water damage can lead to costly repairs if not addressed promptly. Our team handles water damage claims, ensuring your property is restored to its original condition. We provide expert guidance and support throughout the entire process.",
        "vandalismLongDescription": "Vandalism can be both emotionally and financially draining. Our team assists with vandalism claims, helping you recover from property damage and restore your peace of mind. We are committed to providing compassionate and professional service."
    },
    "es": {
        "home": "Inicio",
        "spanish": "Español",
        "heroTitle": "Obtén la Compensación Justa que Mereces",
        "noRecovery": "Sin Recuperación, Sin Honorarios",
        "heroSubtitle": "Luchamos por Ti y por Tus Derechos como Asegurado",
        "heroDescription": "Ajustadores públicos con base en Florida, dedicados a ayudar a los propietarios a maximizar sus reclamaciones de seguros.",
        "freeInspection": "Inspección Gratuita",
        "servicesTitle": "Listado de Servicios",
        "floodDamage": "Daños por Inundación",
        "floodDescription": "Manejamos reclamaciones por daños por inundación para ayudarte a recuperarte rápida y eficientemente.",
        "fireDamage": "Daños por Incendio",
        "fireDescription": "Nuestros expertos ayudan con reclamaciones por daños por incendio para restaurar tu propiedad.",
        "moldRemediation": "Remediación de Moho",
        "moldDescription": "Especializados en reclamaciones por daños de moho para garantizar un ambiente seguro.",
        "hurricaneDamage": "Daños por Huracán",
        "hurricaneDescription": "Te ayudamos a recuperarte de daños por huracán con manejo experto de reclamaciones.",
        "waterDamage": "Daños por Agua",
        "waterDescription": "Nuestro equipo maneja reclamaciones por daños por agua para restaurar tu propiedad.",
        "vandalismClaims": "Reclamaciones por Vandalismo",
        "vandalismDescription": "Ayudamos con reclamaciones por vandalismo para recuperarte de daños a la propiedad.",
        "exploreMoreServices": "Más Información",
        "aboutTitle": "#1 Socio de Confianza para Reclamaciones de Seguros",
        "aboutDescription": "Dynamic Claims Advisors Inc. se dedica a brindar asesoramiento experto y apoyo personalizado para navegar por las reclamaciones de seguros. Ayudamos a individuos y empresas a lograr resultados justos de manera eficiente.",
        "aboutList1": "Orientación Experta para Todo Tipo de Reclamaciones",
        "aboutList2": "Servicio Transparente y Profesional",
        "aboutList3": "Comprometidos con el Éxito del Cliente",
        "aboutButton": "Conoce Más Sobre Nosotros",
        "contactTitle": "Contáctanos",
        "contactDescription": "Estamos aquí para ayudarte. Ponte en contacto con nosotros para consultas, soporte o cualquier otra asistencia que necesites.",
        "contactFormDescription": "Reserva tu inspección gratuita hoy",
        "contactFormName": "Tu Nombre",
        "contactFormEmail": "Tu Correo Electrónico",
        "contactFormSubject": "Asunto",
        "contactFormPhone": "Numero de Teléfono",
        "contactFormMessage": "Mensaje",
        "contactFormNamePlaceholder": "Tu Nombre",
        "contactFormEmailPlaceholder": "Tu Correo Electrónico",
        "contactFormPhonePlaceholder": "Teléfono",
        "contactFormMessagePlaceholder": "Deja un mensaje aquí",
        "contactFormButton": "Enviar Mensaje",
        "ctaTitle": "Conéctate con Nuestro Equipo de Expertos",
        "ctaDescription": "Estamos aquí para ayudarte. Contáctanos para obtener más información sobre nuestros servicios o para programar una consulta.",
        "ctaCallButton": "Hacer una Llamada",
        "ctaAppointmentButton": "Reservar Cita",
        "easyClaimTitle": "Hacer Reclamaciones Nunca Ha Sido Tan Fácil",
        "easyClaimDescription": "Nuestro proceso simplificado está diseñado para que no tengas que preocuparte por los detalles. De principio a fin, te guiamos en cada paso.",
        "easyClaimList1": "Evaluación Gratuita: Comienza con una inspección y consulta gratuita.",
        "easyClaimList2": "Documentación: Nos encargamos de todo el papeleo necesario por ti.",
        "easyClaimList3": "Negociación: Trabajamos directamente con tu compañía de seguros para maximizar tu reclamación.",
        "easyClaimList4": "Resolución Rápida: Recibe tu compensación de manera rápida y sin complicaciones.",
        "easyClaimButton": "Comienza Ahora",
        "testimonialTitle": "Lo Que Dicen Nuestros Clientes",
        "testimonial1": "\"Después de que nuestro hogar fuera dañado por un huracán, este equipo nos guio en cada paso. Su profesionalismo y cuidado hicieron que un proceso estresante fuera mucho más fácil. ¡Altamente recomendados!\"",
        "testimonial2": "\"Gracias a su experiencia, recibimos la compensación completa por los daños de agua en nuestro sótano. El equipo es eficiente, amigable y realmente sabe lo que hace.\"",
        "testimonial3": "\"Nunca pensé que presentar una reclamación de seguros podría ser tan sencillo. Su atención al detalle y comunicación constante me dieron tranquilidad después del daño por incendio en mi propiedad.\"",
        "footerGetInTouch": "Contáctanos",
        "footerQuickLinks": "Enlaces Rápidos",
        "footerAboutUs": "Sobre Nosotros",
        "footerContactUs": "Contáctanos",
        "footerOurServices": "Nuestros Servicios",
        "footerPrivacyPolicy": "Política de Privacidad",
        "footerTermsConditions": "Términos y Condiciones",
        "footerNewsletter": "Boletín Informativo",
        "footerNewsletterDescription": "Mantente actualizado con nuestras últimas noticias y ofertas.",
        "footerNewsletterPlaceholder": "Tu correo electrónico",
        "footerNewsletterButton": "Suscribirse",
        "servicesPageTitle": "Nuestros Servicios",
        "floodLongDescription": "Los daños por inundación pueden ser devastadores, pero nuestro equipo está aquí para ayudarte a recuperarte rápida y eficientemente. Nos encargamos de todos los aspectos de las reclamaciones por daños por inundación, desde la evaluación inicial hasta el acuerdo final. Nuestros expertos trabajan incansablemente para garantizar que recibas la compensación que mereces.",
        "fireLongDescription": "Los daños por incendio pueden dejar tu propiedad en ruinas, pero nuestro equipo está aquí para guiarte en el proceso de recuperación. Ayudamos con las reclamaciones por daños por incendio, ayudándote a restaurar tu propiedad y volver a la normalidad. Nuestro objetivo es hacer que el proceso sea lo más fluido y sin estrés posible.",
        "moldLongDescription": "El moho puede representar serios riesgos para la salud y dañar tu propiedad. Nuestro equipo se especializa en reclamaciones por daños de moho, asegurando un ambiente seguro y saludable para ti y tu familia. Nos encargamos de todos los pasos necesarios para resolver los problemas de moho de manera eficiente.",
        "hurricaneLongDescription": "Los huracanes pueden causar daños extensos a tu propiedad. Nuestro equipo tiene experiencia en el manejo de reclamaciones por daños por huracanes, ayudándote a recuperarte y reconstruir. Trabajamos directamente con tu compañía de seguros para maximizar tu reclamación y garantizar una resolución rápida.",
        "waterLongDescription": "Los daños por agua pueden llevar a reparaciones costosas si no se abordan a tiempo. Nuestro equipo maneja reclamaciones por daños por agua, asegurando que tu propiedad sea restaurada a su estado original. Brindamos orientación experta y apoyo durante todo el proceso.",
        "vandalismLongDescription": "El vandalismo puede ser emocional y financieramente agotador. Nuestro equipo ayuda con las reclamaciones por vandalismo, ayudándote a recuperarte de los daños a la propiedad y restaurar tu tranquilidad. Estamos comprometidos a brindar un servicio compasivo y profesional."
    }
};




let currentLang = 'en'; // Idioma por defecto

function toggleLanguage() {
    currentLang = currentLang === 'en' ? 'es' : 'en';
    translatePage();
}

function translatePage() {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        element.textContent = translations[currentLang][key];
    });
}

document.getElementById('language-toggle').addEventListener('click', toggleLanguage);

// Traducir la página al cargar (opcional)
translatePage();


