const translations = {
    "en": {
        "home": "Home",
        "license": "License: W672811",
        "spanish": "Español",
        "heroTitle": "Get the fair yompensation you deserve",
        "noRecovery": "No Recovery, No Fee",
        "heroSubtitle": "We fight for you and your rights as a policyholder",
        "heroDescription": "Florida-based public adjusters dedicated to helping property owners maximize their insurance claims.",
        "freeInspection": "Free Inspection",
        "servicesTitle": "Services Listing",
        "floodDamage": "Flood Damage",
        "floodDescription": "We handle flood damage claims to help you recover quickly and efficiently.",
        "fireDamage": "Fire Damage",
        "fireDescription": "Our experts assist with fire damage claims to restore your property.",
        "moldRemediation": "Mold Remediation",
        "moldDescription": "We specialize in mold damage claims to ensure a safe environment.",
        "hurricaneDamage": "Hurricane Damage",
        "hurricaneDescription": "We help you recover from hurricane damage with expert claim handling.",
        "waterDamage": "Water Damage",
        "waterDescription": "Our team handles water damage claims to restore your property.",
        "vandalismClaims": "Vandalism Claims",
        "vandalismDescription": "We assist with vandalism claims to help you recover from property damage.",
        "exploreMoreServices": "More Information",
        "aboutTitle": "#1 Trusted partner for insurance claims",
        "aboutDescription": "Dynamic Claims Advisors Inc. is dedicated to providing expert advice and personalized support in navigating insurance claims. We help individuals and businesses achieve fair outcomes efficiently.",
        "aboutList1": "Expert Guidance for All Claim Types",
        "aboutList2": "Transparent and Professional Service",
        "aboutList3": "Committed to Client Success",
        "aboutButton": "Learn More About Us",
        "contactTitle": "Contact Us",
        "contactDescription": "We are here to help. Get in touch with us for inquiries, support, or any other assistance you may need.",
        "contactFormDescription": "Request your free inspection",
        "contactFormName": "Name",
        "contactFormEmail": "Email",
        "contactFormSubject": "Subject",
        "contactFormPhone": "Phone Number",
        "contactFormMessage": "Message",
        "contactFormNamePlaceholder": "Your Name",
        "contactFormEmailPlaceholder": "Your Email",
        "contactFormPhonePlaceholder": "Phone",
        "contactFormMessagePlaceholder": "Leave your message here",
        "contactFormButton": "Send Message",
        "ctaTitle": "Connect with our oxpert team",
        "ctaDescription": "We are here to assist you. Contact us to learn more about our services or to schedule a consultation.",
        "ctaCallButton": "Make A Call",
        "ctaAppointmentButton": "Book Appointment",
        "easyClaimTitle": "Making claims has never been easier",
        "easyClaimDescription": "Our streamlined process is designed so you don’t have to worry about the details. From start to finish, we guide you every step of the way.",
        "easyClaimList1": "Free Evaluation: Begin with a free inspection and consultation.",
        "easyClaimList2": "Documentation :We handle all the required paperwork for you.",
        "easyClaimList3": "Negotiation: We work directly with your insurance company to maximize your claim.",
        "easyClaimList4": "Fast Resolution: Receive your compensation quickly and hassle-free.",
        "easyClaimButton": "Get Started Now",
        "testimonialTitle": "What our clients say",
        "testimonial1": "\"I definitely recomend Dynamic claims advisors inc, Mr. Machuca answer my call and came immediately to help me with my proplem.  He found the best option for my needs.\"",
        "testimonial2": "\"Thank you Dynamic Claims Advisors, Inc. for helping me through my claims process.   My advisor, Hernan M., was very knowledgeable, kind and patient.  He kept me in the loop of things in a timely manner.  The team handled everything professionally and put my mind at ease since I was unfamiliar how to handle these processes.  To top it all off, the outcome was better than what I had expected.  Thank you again, Hernan.- Highly recommend this company!\"",
        "testimonial3": "\"Hernan is helpful, knowledgeable and proactive in resolving cases.\"",
        "footerGetInTouch": "Get In Touch",
        "footerQuickLinks": "Quick Links",
        "footerAboutUs": "About Us",
        "footerContactUs": "Contact Us",
        "footerOurServices": "Our Services",
        "footerPrivacyPolicy": "Privacy Policy",
        "footerTermsConditions": "Terms & Conditions",
        "footerSocialMedia": "Social Media",
        "footerNewsletterDescription": "Stay updated with our latest news and offers.",
        "footerNewsletterPlaceholder": "Your email",
        "footerNewsletterButton": "Sign Up",
        "servicesPageTitle": "Our Services",
        "floodLongDescription": "Flood damage can be devastating, but our team is here to help you recover quickly and efficiently. We handle all aspects of flood damage claims, from initial assessment to final settlement. Our experts work tirelessly to ensure you receive the compensation you deserve.",
        "fireLongDescription": "Fire damage can leave your property in ruins, but our team is here to guide you through the recovery process. We assist with fire damage claims, helping you restore your property and get back on your feet. Our goal is to make the process as smooth and stress-free as possible.",
        "moldLongDescription": "Mold can pose serious health risks and damage your property. Our team specializes in mold damage claims, ensuring a safe and healthy environment for you and your family. We handle all the necessary steps to resolve mold issues efficiently.",
        "hurricaneLongDescription": "Hurricanes can cause extensive damage to your property. Our team is experienced in handling hurricane damage claims, helping you recover and rebuild. We work directly with your insurance company to maximize your claim and ensure a fast resolution.",
        "waterLongDescription": "Water damage can lead to costly repairs if not addressed promptly. Our team handles water damage claims, ensuring your property is restored to its original condition. We provide expert guidance and support throughout the entire process.",
        "vandalismLongDescription": "Vandalism can be both emotionally and financially draining. Our team assists with vandalism claims, helping you recover from property damage and restore your peace of mind. We are committed to providing compassionate and professional service.",
        "part1": "With over 8 years of experience in the market, Hernan Machuca has solidified his position as a leader in insurance claim adjustments within Central Florida. His team of experts work directly with homeowners and businesses to maximize their settlements, ensuring a transparent and efficient process. Committed to advocating for their clients, they offer personalized advice and have a strong track record in resolving claims for hurricane damage,water damage, fires, storms, and more.",
        "part2": "Licensed and certified as a PCA/Loss Consultant, Hernan combines his deep industry knowledge with a client-focused approach to ensure that every claim is handled efficiently and effectively. Whether you're dealing with property damage, business interruptions, or other insurance-related challenges, Hernan’s commitment to delivering results makes him the go-to expert in the field.",
        "part3": "Clients trust Hernan for his proven track record, attention to detail, and ability to navigate the intricacies of the claims process. His dedication to fairness and transparency has earned him the respect of both clients and industry peers alike. When you work with Hernan Machuca, you’re not just hiring a claims advisor – you’re gaining a partner who will fight for your best interests and ensure you receive the compensation you deserve.",
        "contactFormDamageType": "Type of Claim",
    },
    "es": {
        "home": "Inicio",
        "license": "Licencia: W672811",
        "spanish": "Español",
        "heroTitle": "Obtén la compensación justa que mereces",
        "noRecovery": "Si no Recuperas, No Pagas",
        "heroSubtitle": "Luchamos por ti y por tus derechos como asegurado",
        "heroDescription": "Ajustadores públicos con base en Florida, dedicados a ayudar a los propietarios a maximizar sus reclamaciones de seguros.",
        "freeInspection": "Inspección Gratuita",
        "servicesTitle": "Listado de Servicios",
        "floodDamage": "Daños por Inundación",
        "floodDescription": "Manejamos reclamaciones por daños por inundación para ayudarte a recuperarte rápida y eficientemente.",
        "fireDamage": "Daños por Incendio",
        "fireDescription": "Nuestros expertos ayudan con reclamaciones por daños por incendio para restaurar tu propiedad.",
        "moldRemediation": "Remediación de Moho",
        "moldDescription": "Especializados en reclamaciones por daños de moho para garantizar un ambiente seguro.",
        "hurricaneDamage": "Daños por Huracán",
        "hurricaneDescription": "Te ayudamos a recuperarte de daños por huracán con manejo experto de reclamaciones.",
        "waterDamage": "Daños por Agua",
        "waterDescription": "Nuestro equipo maneja reclamaciones por daños por agua para restaurar tu propiedad.",
        "vandalismClaims": "Reclamaciones por Vandalismo",
        "vandalismDescription": "Ayudamos con reclamaciones por vandalismo para recuperarte de daños a la propiedad.",
        "exploreMoreServices": "Más Información",
        "aboutTitle": "#1 Socio de confianza para reclamaciones de seguros",
        "aboutDescription": "Dynamic Claims Advisors Inc. se dedica a brindar asesoramiento experto y apoyo personalizado para navegar por las reclamaciones de seguros. Ayudamos a individuos y empresas a lograr resultados justos de manera eficiente.",
        "aboutList1": "Orientación experta para todo tipo de reclamaciones",
        "aboutList2": "Servicio transparente y profesional",
        "aboutList3": "Comprometidos con el exito del cliente",
        "aboutButton": "Conoce Más Sobre Nosotros",
        "contactTitle": "Contáctanos",
        "contactDescription": "Estamos aquí para ayudarte. Ponte en contacto con nosotros para consultas, soporte o cualquier otra asistencia que necesites.",
        "contactFormDescription": "Reserva tu inspección gratuita hoy",
        "contactFormName": "Tu Nombre",
        "contactFormEmail": "Tu Correo Electrónico",
        "contactFormSubject": "Asunto",
        "contactFormPhone": "Numero de Teléfono",
        "contactFormMessage": "Mensaje",
        "contactFormNamePlaceholder": "Tu Nombre",
        "contactFormEmailPlaceholder": "Tu Correo Electrónico",
        "contactFormPhonePlaceholder": "Teléfono",
        "contactFormMessagePlaceholder": "Deja un mensaje aquí",
        "contactFormButton": "Enviar Mensaje",
        "ctaTitle": "Conéctate con Nuestro Equipo de Expertos",
        "ctaDescription": "Estamos aquí para ayudarte. Contáctanos para obtener más información sobre nuestros servicios o para programar una consulta.",
        "ctaCallButton": "Hacer una Llamada",
        "ctaAppointmentButton": "Reservar Cita",
        "easyClaimTitle": "Hacer reclamaciones nunca ha sido tan fácil",
        "easyClaimDescription": "Nuestro proceso simplificado está diseñado para que no tengas que preocuparte por los detalles. De principio a fin, te guiamos en cada paso.",
        "easyClaimList1": "Evaluación Gratuita: Comienza con una inspección y consulta gratuita.",
        "easyClaimList2": "Documentación: Nos encargamos de todo el papeleo necesario por ti.",
        "easyClaimList3": "Negociación: Trabajamos directamente con tu compañía de seguros para maximizar tu reclamación.",
        "easyClaimList4": "Resolución Rápida: Recibe tu compensación de manera rápida y sin complicaciones.",
        "easyClaimButton": "Comienza Ahora",
        "testimonialTitle": "Lo que dicen nuestros clientes",
        "testimonial1": "\"Definitivamente recomiendo Dynamic Claims Advisors Inc. El Sr. Machuca respondió mi llamada y vino inmediatamente a ayudarme con mi problema. Encontró la mejor opción para mis necesidades.\"",
        "testimonial2": "\"Gracias a Dynamic Claims Advisors, Inc. por ayudarme en el proceso de mis reclamos. Mi asesor, Hernan M., fue muy conocedor, amable y paciente. Me mantuvo informado de todo de manera oportuna. El equipo manejó todo de manera profesional y me tranquilizó, ya que no estaba familiarizado con cómo manejar estos procesos. Para colmo, el resultado fue mejor de lo que esperaba. Gracias de nuevo, Hernan. ¡Recomiendo ampliamente esta empresa!\"",
        "testimonial3": "\"Hernan es servicial, conocedor y proactivo en la resolución de casos.\"",
        "footerGetInTouch": "Contáctanos",
        "footerQuickLinks": "Enlaces Rápidos",
        "footerAboutUs": "Sobre Nosotros",
        "footerContactUs": "Contáctanos",
        "footerOurServices": "Nuestros Servicios",
        "footerPrivacyPolicy": "Política de Privacidad",
        "footerTermsConditions": "Términos y Condiciones",
        "footerSocialMedia": "Redes Sociales",
        "footerNewsletterDescription": "Mantente actualizado con nuestras últimas noticias y ofertas.",
        "footerNewsletterPlaceholder": "Tu correo electrónico",
        "footerNewsletterButton": "Suscribirse",
        "servicesPageTitle": "Nuestros Servicios",
        "floodLongDescription": "Los daños por inundación pueden ser devastadores, pero nuestro equipo está aquí para ayudarte a recuperarte rápida y eficientemente. Nos encargamos de todos los aspectos de las reclamaciones por daños por inundación, desde la evaluación inicial hasta el acuerdo final. Nuestros expertos trabajan incansablemente para garantizar que recibas la compensación que mereces.",
        "fireLongDescription": "Los daños por incendio pueden dejar tu propiedad en ruinas, pero nuestro equipo está aquí para guiarte en el proceso de recuperación. Ayudamos con las reclamaciones por daños por incendio, ayudándote a restaurar tu propiedad y volver a la normalidad. Nuestro objetivo es hacer que el proceso sea lo más fluido y sin estrés posible.",
        "moldLongDescription": "El moho puede representar serios riesgos para la salud y dañar tu propiedad. Nuestro equipo se especializa en reclamaciones por daños de moho, asegurando un ambiente seguro y saludable para ti y tu familia. Nos encargamos de todos los pasos necesarios para resolver los problemas de moho de manera eficiente.",
        "hurricaneLongDescription": "Los huracanes pueden causar daños extensos a tu propiedad. Nuestro equipo tiene experiencia en el manejo de reclamaciones por daños por huracanes, ayudándote a recuperarte y reconstruir. Trabajamos directamente con tu compañía de seguros para maximizar tu reclamación y garantizar una resolución rápida.",
        "waterLongDescription": "Los daños por agua pueden llevar a reparaciones costosas si no se abordan a tiempo. Nuestro equipo maneja reclamaciones por daños por agua, asegurando que tu propiedad sea restaurada a su estado original. Brindamos orientación experta y apoyo durante todo el proceso.",
        "vandalismLongDescription": "El vandalismo puede ser emocional y financieramente agotador. Nuestro equipo ayuda con las reclamaciones por vandalismo, ayudándote a recuperarte de los daños a la propiedad y restaurar tu tranquilidad. Estamos comprometidos a brindar un servicio compasivo y profesional.",
        "part1": "Con 8 años de experiencia en el mercado, Hernan Machuca se ha consolidado como un referente en el ajuste de reclamaciones de seguros en Florida Central. Su equipo de expertos trabaja directamente con propietarios de viviendas y negocios para maximizar sus indemnizaciones, asegurando un proceso transparente y eficiente. Comprometidos con la defensa de sus clientes, ofrecen asesoría personalizada y una sólida trayectoria en la resolución de reclamaciones por huracanes, daños por agua, incendios, tormentas y más.",
        "part2": "Licenciado y certificado como PCA/Consultor de Pérdidas, Hernan combina su profundo conocimiento del sector con un enfoque centrado en el cliente para garantizar que cada reclamación se maneje de manera eficiente y efectiva. Ya sea que esté enfrentando daños a la propiedad, interrupciones comerciales u otros desafíos relacionados con seguros, el compromiso de Hernan con la obtención de resultados lo convierte en el experto de referencia en el campo.",
        "part3": "Los clientes confían en Hernan por su historial comprobado, atención al detalle y capacidad para navegar por las complejidades del proceso de reclamaciones. Su dedicación a la equidad y la transparencia le ha valido el respeto tanto de los clientes como de sus colegas en la industria. Cuando trabaja con Hernan Machuca, no solo está contratando a un asesor en reclamaciones, está ganando un aliado que luchará por sus mejores intereses y asegurará que reciba la compensación que merece.",
        "contactFormDamageType": "Tipo de Daño",

    }
};




let currentLang = 'en'; // Idioma por defecto

function toggleLanguage() {
    currentLang = currentLang === 'en' ? 'es' : 'en';
    translatePage();
}

function translatePage() {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        element.textContent = translations[currentLang][key];
    });
}

document.getElementById('language-toggle').addEventListener('click', toggleLanguage);

// Traducir la página al cargar (opcional)
translatePage();


